version: '3.8'

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    ports:
      - 5432:5432 # local:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean