version: '3.8'

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    ports:
      - 5433:5432 # local:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres